name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Install Cargo Hack
      run: cargo install --debug cargo-hack
    - name: Tests
      run: cargo hack test --workspace --feature-powerset
  Clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add Clippy
      run: rustup component add clippy
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Check Clippy
      run: cargo clippy --all-features -- -D warnings
  Rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Add rustfmt
      run: rustup component add rustfmt
    - name: Rustc version
      run: rustc -Vv
    - name: Cargo version
      run: cargo -Vv
    - name: Check formatting
      run: cargo fmt --all -- --check
  Docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features
